#! /bin/bash
set -e

MY_COLOR_BLUE='\033[0;34m'
MY_COLOR_BOLD_BLUE='\033[1;34m'
MY_DIVIDER="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "

# Ensure that adb binary is in the path
if ! which adb > /dev/null; then
    echo "Cannot find adb: Check that PATH contains platform tools (e.g. \$HOME/Library/Android/sdk/platform-tools)"
    exit 1
fi

# Use Gradle to build APK package
./gradlew assembleDebug

# Install the APK on the virtual device (-r replaces any existing one)
adb install -r app/build/outputs/apk/app-debug.apk

# Clear log cat
adb logcat -c

# Start the main activity
adb shell am start -n com.node22.breadcrumbs/.MainActivity

# Show dividing line
echo -e "${MY_COLOR_BLUE}$MY_DIVIDER"
echo -e "${MY_COLOR_BOLD_BLUE}Begin log messages" 
echo -e "${MY_COLOR_BLUE}$MY_DIVIDER"

# Show log of errors and/or log messages matching package
adb logcat | ack '^E/AndroidRuntime|^./*com.node22.breadcrumbs'
