#! /bin/bash
set -e

MY_COLOR_BLUE='\033[0;34m'
MY_COLOR_BOLD_BLUE='\033[1;34m'
MY_DIVIDER="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "
MY_APP="com.node22.breadcrumbs"

# Ensure that adb binary is in the path
if ! which adb > /dev/null; then
    echo "Cannot find adb: Check that PATH contains platform tools (e.g. \$HOME/Library/Android/sdk/platform-tools)"
    exit 1
fi

# When no parameter is given, rebuild first
if [ -z "$1" ]; then
    # Use Gradle to build APK package
    ./gradlew assembleDebug
fi

# Install the APK on the virtual device (-r replaces any existing one)
adb install -r app/build/outputs/apk/app-debug.apk

# Clear log cat
adb logcat -c

# Start the main activity
adb shell am start -n $MY_APP/.MainActivity

# Get pid
MY_PID=`adb shell ps | grep com.node22.breadcrumbs | awk '{print $2}'`

echo "PID of running process is: $MY_PID"

# Show dividing line
echo -e "${MY_COLOR_BLUE}$MY_DIVIDER"
echo -e "${MY_COLOR_BOLD_BLUE}Begin log messages" 
echo -e "${MY_COLOR_BLUE}$MY_DIVIDER"

# Show log of errors and/or log messages matching package
# e.g.
# D/com.node22.breadcrumbs( 3745): MainActivity::onCreate
adb logcat | ack "^(E/.+|./*$MY_APP)\\(\\s*$MY_PID\\):"
